version: '3'

services:
  # Auth Service and Database
  auth_db:
    image: postgres:16
    ports:
      - "5433:5432"
    volumes:
      - postgres_users_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=auth_db
      - POSTGRES_PORT=5432

  auth_service:
    build: ./AuthService
    ports:
      - "8000:8000"
    depends_on:
      - auth_db
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:12345@auth_db/auth_db
    volumes:
      - ./AuthService:/app

  # Task Service and Database
  tasks_db:
    image: postgres:16
    ports:
      - "5434:5432"
    volumes:
      - postgres_tasks_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=tasks_db
      - POSTGRES_PORT=5433

  task_service:
    build: ./TaskService
    ports:
      - "50051:50051"
    depends_on:
      - tasks_db
    environment:
      - DATABASE_URL=postgresql://postgres:12345@tasks_db/tasks_db
    volumes:
      - ./TaskService:/app

volumes:
  postgres_users_data:
    external: true
  postgres_tasks_data:
    external: true