# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12task_service.proto\x12\x04task\"\\\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x11\n\tauthor_id\x18\x04 \x01(\x05\x12\x11\n\tcompleted\x18\x05 \x01(\x08\"J\n\x11\x43reateTaskRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x11\n\tauthor_id\x18\x03 \x01(\x05\"i\n\x11UpdateTaskRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x11\n\tauthor_id\x18\x04 \x01(\x05\x12\x11\n\tcompleted\x18\x05 \x01(\x08\"2\n\x11\x44\x65leteTaskRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tauthor_id\x18\x02 \x01(\x05\"\x1c\n\x0eGetTaskRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"2\n\x10ListTasksRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x10\n\x08per_page\x18\x02 \x01(\x05\"8\n\x0cTaskResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x18\n\x04task\x18\x02 \x01(\x0b\x32\n.task.Task\"S\n\x11ListTasksResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x19\n\x05tasks\x18\x02 \x03(\x0b\x32\n.task.Task\x12\x13\n\x0btotal_count\x18\x03 \x01(\x05\x32\xb1\x02\n\x0bTaskService\x12\x39\n\nCreateTask\x12\x17.task.CreateTaskRequest\x1a\x12.task.TaskResponse\x12\x39\n\nUpdateTask\x12\x17.task.UpdateTaskRequest\x1a\x12.task.TaskResponse\x12\x39\n\nDeleteTask\x12\x17.task.DeleteTaskRequest\x1a\x12.task.TaskResponse\x12\x33\n\x07GetTask\x12\x14.task.GetTaskRequest\x1a\x12.task.TaskResponse\x12<\n\tListTasks\x12\x16.task.ListTasksRequest\x1a\x17.task.ListTasksResponseb\x06proto3')



_TASK = DESCRIPTOR.message_types_by_name['Task']
_CREATETASKREQUEST = DESCRIPTOR.message_types_by_name['CreateTaskRequest']
_UPDATETASKREQUEST = DESCRIPTOR.message_types_by_name['UpdateTaskRequest']
_DELETETASKREQUEST = DESCRIPTOR.message_types_by_name['DeleteTaskRequest']
_GETTASKREQUEST = DESCRIPTOR.message_types_by_name['GetTaskRequest']
_LISTTASKSREQUEST = DESCRIPTOR.message_types_by_name['ListTasksRequest']
_TASKRESPONSE = DESCRIPTOR.message_types_by_name['TaskResponse']
_LISTTASKSRESPONSE = DESCRIPTOR.message_types_by_name['ListTasksResponse']
Task = _reflection.GeneratedProtocolMessageType('Task', (_message.Message,), {
  'DESCRIPTOR' : _TASK,
  '__module__' : 'task_service_pb2'
  # @@protoc_insertion_point(class_scope:task.Task)
  })
_sym_db.RegisterMessage(Task)

CreateTaskRequest = _reflection.GeneratedProtocolMessageType('CreateTaskRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATETASKREQUEST,
  '__module__' : 'task_service_pb2'
  # @@protoc_insertion_point(class_scope:task.CreateTaskRequest)
  })
_sym_db.RegisterMessage(CreateTaskRequest)

UpdateTaskRequest = _reflection.GeneratedProtocolMessageType('UpdateTaskRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATETASKREQUEST,
  '__module__' : 'task_service_pb2'
  # @@protoc_insertion_point(class_scope:task.UpdateTaskRequest)
  })
_sym_db.RegisterMessage(UpdateTaskRequest)

DeleteTaskRequest = _reflection.GeneratedProtocolMessageType('DeleteTaskRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETETASKREQUEST,
  '__module__' : 'task_service_pb2'
  # @@protoc_insertion_point(class_scope:task.DeleteTaskRequest)
  })
_sym_db.RegisterMessage(DeleteTaskRequest)

GetTaskRequest = _reflection.GeneratedProtocolMessageType('GetTaskRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETTASKREQUEST,
  '__module__' : 'task_service_pb2'
  # @@protoc_insertion_point(class_scope:task.GetTaskRequest)
  })
_sym_db.RegisterMessage(GetTaskRequest)

ListTasksRequest = _reflection.GeneratedProtocolMessageType('ListTasksRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTTASKSREQUEST,
  '__module__' : 'task_service_pb2'
  # @@protoc_insertion_point(class_scope:task.ListTasksRequest)
  })
_sym_db.RegisterMessage(ListTasksRequest)

TaskResponse = _reflection.GeneratedProtocolMessageType('TaskResponse', (_message.Message,), {
  'DESCRIPTOR' : _TASKRESPONSE,
  '__module__' : 'task_service_pb2'
  # @@protoc_insertion_point(class_scope:task.TaskResponse)
  })
_sym_db.RegisterMessage(TaskResponse)

ListTasksResponse = _reflection.GeneratedProtocolMessageType('ListTasksResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTTASKSRESPONSE,
  '__module__' : 'task_service_pb2'
  # @@protoc_insertion_point(class_scope:task.ListTasksResponse)
  })
_sym_db.RegisterMessage(ListTasksResponse)

_TASKSERVICE = DESCRIPTOR.services_by_name['TaskService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TASK._serialized_start=28
  _TASK._serialized_end=120
  _CREATETASKREQUEST._serialized_start=122
  _CREATETASKREQUEST._serialized_end=196
  _UPDATETASKREQUEST._serialized_start=198
  _UPDATETASKREQUEST._serialized_end=303
  _DELETETASKREQUEST._serialized_start=305
  _DELETETASKREQUEST._serialized_end=355
  _GETTASKREQUEST._serialized_start=357
  _GETTASKREQUEST._serialized_end=385
  _LISTTASKSREQUEST._serialized_start=387
  _LISTTASKSREQUEST._serialized_end=437
  _TASKRESPONSE._serialized_start=439
  _TASKRESPONSE._serialized_end=495
  _LISTTASKSRESPONSE._serialized_start=497
  _LISTTASKSRESPONSE._serialized_end=580
  _TASKSERVICE._serialized_start=583
  _TASKSERVICE._serialized_end=888
# @@protoc_insertion_point(module_scope)
