# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stat_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12stat_service.proto\x12\nstatistics\"\x07\n\x05\x45mpty\"\x1d\n\x0fTaskStatRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"0\n\x10TaskStatResponse\x12\r\n\x05likes\x18\x01 \x01(\x05\x12\r\n\x05views\x18\x02 \x01(\x05\"\'\n\x12PopularTaskRequest\x12\x11\n\tsort_type\x18\x01 \x01(\t\"7\n\x07TaskRsp\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tauthor_id\x18\x02 \x01(\t\x12\r\n\x05\x63ount\x18\x03 \x01(\x05\"A\n\x13PopularTaskResponse\x12*\n\rpopular_tasks\x18\x01 \x03(\x0b\x32\x13.statistics.TaskRsp\"+\n\x07UserRsp\x12\x11\n\tauthor_id\x18\x01 \x01(\x05\x12\r\n\x05likes\x18\x02 \x01(\x05\"A\n\x13PopularUserResponse\x12*\n\rpopular_users\x18\x01 \x03(\x0b\x32\x13.statistics.UserRsp2\xfa\x01\n\x10StatisticService\x12M\n\x10GetTaskStatistic\x12\x1b.statistics.TaskStatRequest\x1a\x1c.statistics.TaskStatResponse\x12Q\n\x0eGetPopularTask\x12\x1e.statistics.PopularTaskRequest\x1a\x1f.statistics.PopularTaskResponse\x12\x44\n\x0eGetPopularUser\x12\x11.statistics.Empty\x1a\x1f.statistics.PopularUserResponseb\x06proto3')



_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_TASKSTATREQUEST = DESCRIPTOR.message_types_by_name['TaskStatRequest']
_TASKSTATRESPONSE = DESCRIPTOR.message_types_by_name['TaskStatResponse']
_POPULARTASKREQUEST = DESCRIPTOR.message_types_by_name['PopularTaskRequest']
_TASKRSP = DESCRIPTOR.message_types_by_name['TaskRsp']
_POPULARTASKRESPONSE = DESCRIPTOR.message_types_by_name['PopularTaskResponse']
_USERRSP = DESCRIPTOR.message_types_by_name['UserRsp']
_POPULARUSERRESPONSE = DESCRIPTOR.message_types_by_name['PopularUserResponse']
Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'stat_service_pb2'
  # @@protoc_insertion_point(class_scope:statistics.Empty)
  })
_sym_db.RegisterMessage(Empty)

TaskStatRequest = _reflection.GeneratedProtocolMessageType('TaskStatRequest', (_message.Message,), {
  'DESCRIPTOR' : _TASKSTATREQUEST,
  '__module__' : 'stat_service_pb2'
  # @@protoc_insertion_point(class_scope:statistics.TaskStatRequest)
  })
_sym_db.RegisterMessage(TaskStatRequest)

TaskStatResponse = _reflection.GeneratedProtocolMessageType('TaskStatResponse', (_message.Message,), {
  'DESCRIPTOR' : _TASKSTATRESPONSE,
  '__module__' : 'stat_service_pb2'
  # @@protoc_insertion_point(class_scope:statistics.TaskStatResponse)
  })
_sym_db.RegisterMessage(TaskStatResponse)

PopularTaskRequest = _reflection.GeneratedProtocolMessageType('PopularTaskRequest', (_message.Message,), {
  'DESCRIPTOR' : _POPULARTASKREQUEST,
  '__module__' : 'stat_service_pb2'
  # @@protoc_insertion_point(class_scope:statistics.PopularTaskRequest)
  })
_sym_db.RegisterMessage(PopularTaskRequest)

TaskRsp = _reflection.GeneratedProtocolMessageType('TaskRsp', (_message.Message,), {
  'DESCRIPTOR' : _TASKRSP,
  '__module__' : 'stat_service_pb2'
  # @@protoc_insertion_point(class_scope:statistics.TaskRsp)
  })
_sym_db.RegisterMessage(TaskRsp)

PopularTaskResponse = _reflection.GeneratedProtocolMessageType('PopularTaskResponse', (_message.Message,), {
  'DESCRIPTOR' : _POPULARTASKRESPONSE,
  '__module__' : 'stat_service_pb2'
  # @@protoc_insertion_point(class_scope:statistics.PopularTaskResponse)
  })
_sym_db.RegisterMessage(PopularTaskResponse)

UserRsp = _reflection.GeneratedProtocolMessageType('UserRsp', (_message.Message,), {
  'DESCRIPTOR' : _USERRSP,
  '__module__' : 'stat_service_pb2'
  # @@protoc_insertion_point(class_scope:statistics.UserRsp)
  })
_sym_db.RegisterMessage(UserRsp)

PopularUserResponse = _reflection.GeneratedProtocolMessageType('PopularUserResponse', (_message.Message,), {
  'DESCRIPTOR' : _POPULARUSERRESPONSE,
  '__module__' : 'stat_service_pb2'
  # @@protoc_insertion_point(class_scope:statistics.PopularUserResponse)
  })
_sym_db.RegisterMessage(PopularUserResponse)

_STATISTICSERVICE = DESCRIPTOR.services_by_name['StatisticService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=34
  _EMPTY._serialized_end=41
  _TASKSTATREQUEST._serialized_start=43
  _TASKSTATREQUEST._serialized_end=72
  _TASKSTATRESPONSE._serialized_start=74
  _TASKSTATRESPONSE._serialized_end=122
  _POPULARTASKREQUEST._serialized_start=124
  _POPULARTASKREQUEST._serialized_end=163
  _TASKRSP._serialized_start=165
  _TASKRSP._serialized_end=220
  _POPULARTASKRESPONSE._serialized_start=222
  _POPULARTASKRESPONSE._serialized_end=287
  _USERRSP._serialized_start=289
  _USERRSP._serialized_end=332
  _POPULARUSERRESPONSE._serialized_start=334
  _POPULARUSERRESPONSE._serialized_end=399
  _STATISTICSERVICE._serialized_start=402
  _STATISTICSERVICE._serialized_end=652
# @@protoc_insertion_point(module_scope)
