openapi: 3.0.0
info:
  title: User Tracker API
  version: 1.0.0
servers:
  - url: http://localhost:8000
paths:
  /register:
    post:
      summary: Register new user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  format: username
                password:
                  type: string
                  format: password
                first_name:
                  type: string
                  format: first_name
                last_name:
                  type: string
                  format: last_name
                birthdate:
                  type: string
                  format: date
                email:
                  type: string
                  format: email
                phone_number:
                  type: string
                  format: phone_number
      responses:
        '200':
          description: User registered successfully
  /update/:
    put:
      summary: Update user data
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  format: first_name
                last_name:
                  type: string
                  format: last_name
                birthdate:
                  type: string
                  format: date
                email:
                  type: string
                  format: email
                phone_number:
                  type: string
                  format: phone_number
      responses:
        '200':
          description: User updated successfully
  /login:
    post:
      summary: Login user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  format: username
                password:
                  type: string
                  format: password
      responses:
        '200':
          description: Login successful
  /logout:
    post:
      summary: Logout user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  format: token
      responses:
        '200':
          description: Logout successful
